# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_models.MLP.ipynb (unless otherwise specified).

__all__ = ['MLP1', 'MLP2']

# Cell
def MLP1(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def MLP2(to):
    "Say hello to somebody"
    return f'Hello {to}!'